name: drift_inspector
description: A dart library to enable development time inspection and modification of your drift databases
version: 1.0.1
homepage: https://github.com/Chimerapps/drift_inspector

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_service_announcement: ^1.0.0
  drift: ^1.0.1
  synchronized: ^3.0.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.0.5
  drift_dev: ^1.0.2
  lints: ^1.0.1
