name: example
description: A sample command-line application.
version: 1.0.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
   drift: ^1.0.1
   drift_inspector:

dev_dependencies:
  build_runner: ^2.0.5
  drift_dev: ^1.0.2
  lints: ^1.0.1

dependency_overrides:
  drift_inspector:
    path: ..