name: moor_inspector
description: A dart library to enable development time inspection and modification of your moor databases
version: 0.2.0-nullsafety.0
homepage: https://github.com/Chimerapps/moor_inspector

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  dart_service_announcement: ^1.0.0-nullsafety.1
  moor: ^4.0.0-nullsafety.1
  synchronized: ^3.0.0-nullsafety.1

dev_dependencies:
  build_runner: ^1.10.4
  pedantic: ^1.9.0
  #moor_generator: ^4.0.0-dev Only used to generate the example, blocks nullsafety release due to logging