name: moor_inspector
description: A dart library to enable development time inspection and modification of your moor databases
version: 0.1.3
homepage: https://github.com/Chimerapps/moor_inspector

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  dart_service_announcement: ^0.2.1
  meta: ^1.1.8
  moor: ^3.4.0
  synchronized: ^2.1.0
  uuid: ^2.0.1

dev_dependencies:
  build_runner: ^1.10.4
  moor_generator: ^3.4.0
  pedantic: ^1.9.0
  test: ^1.14.4
