name: moor_inspector
description: A dart library to enable development time inspection and modification of your moor databases
version: 0.3.1
homepage: https://github.com/Chimerapps/moor_inspector

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_service_announcement: ^1.0.0
  moor: ^4.4.0
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.5
  moor_generator: ^4.4.0
  pedantic: ^1.11.1